### ISSUE TITLE
Improve readme / documentation

### ISSUE THREAD

**Issue by ndelangen** [storybookjs/addon-smart-knobs#1]
This sounds really promising!, but the documentation / readme does not provide enough information on it's own to be able to determine what this addon exactly does.

**Comment by lucasconstantino** [comment]
Hi there! This Storybook plugin uses [storybook-addon-knobs](https://github.com/kadirahq/storybook-addon-knobs) but creates the knobs automatically based on PropTypes. I'm still testing and trying it, therefore a didn't really push the documentation forward.

For more information, have a look here: https://github.com/kadirahq/storybook-addon-knobs/issues/63

**Comment by ndelangen** [comment]
I might start using it, so added some minimal info in de readme here https://github.com/lucasconstantino/storybook-addon-smart-knobs/pull/2
