### ISSUE TITLE
SmartKnobs does not work with Info

### ISSUE THREAD

**Issue by danielduan** [storybookjs/addon-smart-knobs#11]
Info and SmartKnobs doesn't seem to work together. When I replace `addWithInfo` with `add`, the SmartKnobs appear in the Knobs panel. It doesn't otherwise.

```
import React from 'react';
import { storiesOf } from '@storybook/react';
const ProgressBar = require('shared/components/ProgressBar');

import { withSmartKnobs } from 'storybook-addon-smart-knobs';
import { withKnobs } from '@storybook/addon-knobs';

storiesOf('ProgressBar', module)
  .addDecorator(withSmartKnobs)
  .addDecorator(withKnobs)
  .addWithInfo('default style', () => (
    <ProgressBar />
  ));

```

**Comment by ndelangen** [comment]
@shilman Will one of these days refactor info to render in a panel. Maybe that will fix this?

**Comment by husayt** [comment]
@shilman  are there any updates on this?  There were lots of cool improvements around add-info lately, but this issue is still there unfortunately.

thanks

**Comment by flipace** [comment]
@husayt  @ndelangen i made a PR which fixes this issue - it should also work after the info panel addons render logic was changed.
