### ISSUE TITLE
Update the docs and/or dependencies to indicate the dependency on babel-plugin-react-docgen

### ISSUE THREAD

**Issue by mkochendorfer** [storybookjs/addon-smart-knobs#17]
Nowhere in the docs or dependencies does this project indicate that https://github.com/storybooks/babel-plugin-react-docgen is needed in order for it to work.  That package should either be moved from the devDependencies to peerDependencies and/or documentation should be added to the README indicating that it is needed.

**Comment by alexhalf** [comment]
Yes and what the plugin can not work together with flow-react-proptypes in storybook, what very strange for me, but types does not have any __docgen properties.
