### ISSUE TITLE
React 16 Support?

### ISSUE THREAD

**Issue by KamalAman** [storybookjs/addon-smart-knobs#18]
I've tried to use smark knobs with react v16, and I cannot get anything to display or show up in the Knobs viewer.

**Comment by ndelangen** [comment]
Hi @KamalAman,

Do you think you'd be able to debug the problem and open a PR with a fix? 🙇

**Comment by KamalAman** [comment]
The issue seems to be with docgen being undefined on the button in the `Usage` example when using React 16.

The following describes the issue.
https://github.com/storybooks/storybook/issues/1762
https://github.com/storybooks/babel-plugin-react-docgen/issues/33

Other than the root problem with Doc gen performing some magical parsing, the `Usage` documentation for `addon-smart-knobs` does not accurately describe what needs to be done with React 16. 

Button needs to be defined in another file than the story, and it needs to be the default export of that file.

**Comment by chrisjaure** [comment]
I think this may be related to a storybook change. It was working for me fine in 3.2, but once I upgraded to 3.3, the knobs weren't showing anymore.

It seems to be related to the marksyConf check here: https://github.com/storybooks/addon-smart-knobs/blob/6eb5cb767cb4e0fbbfb95b11384bf38df96db3e6/src/index.js#L60

and here: https://github.com/storybooks/addon-smart-knobs/blob/6eb5cb767cb4e0fbbfb95b11384bf38df96db3e6/src/index.js#L86

Once I removed the checks, it started working again.

What use-case are these checks serving?

**Comment by chrisjaure** [comment]
Ah I see it was added to support using `withInfo` (which I am), but that addon has change in this commit: https://github.com/storybooks/storybook/commit/170f3eb54ad621fab2f6296a3de05448b8e48d52#diff-c944184f73b67670ca1f8d8e29108c12

I wonder if this is a separate issue?

**Comment by ndelangen** [comment]
Released with `3.3.0`

**Comment by Hypnosphi** [comment]
@ndelangen we should raise all the `@storybook` peerDeps to `3.3`

**Comment by ndelangen** [comment]
Done, and published as `3.3.1` @Hypnosphi
