### ISSUE TITLE
TypeScript support?

### ISSUE THREAD

**Issue by kotarella1110** [storybookjs/addon-smart-knobs#25]
Do you have a plan to support to TypeScript?

**Comment by frosato-dev** [comment]
@kotarella1110, I was able to make it work with typescript by using [this webpack loader](https://www.npmjs.com/package/react-docgen-typescript-loader).
It will help you by converting your (typescript) types into propTypes.
You need to add it to your `.strorybook/webpack.config.js`.
So far, i made it work for primitive types only (string, boolean, ...).

**Comment by mhauens** [comment]
Just managed to get string in the Knobs by using this webpack loader. But no oneOf or boolean. In the Prop Types section the props are shown, but don't appear in the smart-knobs-addon. See screenshot: https://imgur.com/a/RTv7sqc

**Comment by mhauens** [comment]
checkbox.tsx:

```
interface IProps {
   /** Specifies the id of the checkbox */
    id: string;
    /** Specifies a testid for testing the checkbox */
    testid: string;
    /** The onChange event fires the moment when the value of the element is changed. */
    onChange: () => void;
    /** The onBlur event fires the moment that the element loses focus. */
    onBlur?: () => void;
    /** The onFocus event fires the moment when the element gets focus. */
    onFocus?: () => void;
    /**
     * Specifies a name for the checkbox
     * @default ""
     */
    name?: string;
    /**
     * Specifies a label for the checkbox
     * @default ""
     */
    label?: string;
    /**
     * Specifies the size for the checkbox
     * @default "medium"
     */
    size?: "small" | "medium" | "large";
    /**
     * Sets the checkbox to disabled
     * @default false
     */
    disabled?: boolean;
    /**
     * If set to true, the label is before the checkbox
     * @default false
     */
    labelBefore?: boolean;
    /**
     * Specifies the state for the checkbox.
     * @default ""
     */
    state?: "success" | "warning" | "error";
    /**
     * Specifies the value of the checkbox
     * @default ""
     */
    value?: string;
    /**
     * Specifies if the checkbox is checked
     * @default false
     */
    checked?: boolean;
}

/** Checkbox component description text */
const Checkbox = (props: IProps) => {
...
};
```

checkbox.story.tsx

```
import React from "react";
...
import { withKnobs } from "@storybook/addon-knobs/react";
import { withSmartKnobs } from "storybook-addon-smart-knobs";
...

storiesOf("Form-Elements", module)
    .addDecorator(withSmartKnobs)
    .addDecorator(withKnobs)
    ...
    .add(
        "Checkbox",
        withInfo()(() => (
            <Checkbox
                label="Checkbox"
                id="checkboxId"
                testid="checkboxId"
                onChange={action("onChange")}
                onBlur={action("onBlur")}
                onFocus={action("onFocus")}
            />
        ))
    );
```

**Comment by mhauens** [comment]
@frosato-ekino Do you have any suggestion to make the e.g.

```
checked?: boolean;
size?: "small" | "medium" | "large";
```
appear in the Knobs section as a checkbox and as a selectbox?

like it does if you are in a js file and use e.g.

```
Checkbox.propTypes = {
     /** Specifies if the checkbox is checked */
    checked: PropTypes.bool,
    /** Specifies the size for the checkbox */
    size: PropTypes.oneOf(["small", "medium", "large"])
};
```
like this one (done in .js not in .tsx): https://imgur.com/a/0mhvdRt

**Comment by frosato-dev** [comment]
@mhauens Like I said above, I used [react-docgen-typescript-loader](https://www.npmjs.com/package/react-docgen-typescript-loader) to convert my typescript into propTypes. It works very well with primitive types (number, string, boolean) but it was definitly not working as expected with enum ("small" | "medium" | "large"). [I followed the doc for the setup](https://storybook.js.org/configurations/typescript-config/#setting-up-typescript-to-work-with-storybook)
`addon-smart-knobs` is based on propTypes, so yeah, I got the checkbox working for boolean propTypes but select didn't showup.
I had no extra time to investigate so i stop using this addon for now, i'll give it an other shot soon.
If you find anything let me know

**Comment by mhauens** [comment]
@strothj Do you may have any idea, because you did the react-docgen-typescript-loader?

**Comment by strothj** [comment]
I wasn't familiar with this addon before now.

Fortunately, this addon is not using prop types directly. It is using docgen information that is attached by the built in docgen loader (or the one from the TypeScript loader).

This should be fixable from either the addon's side or the loader.

Basically, we need to have output from the TypeScript loader match the expected structure for this addon or the addon can be changed to recognize the pattern from the TypeScript loader.

A property called `__docgenInfo` is attached to React components by both of the loaders with the information that is parsed by both this addon and addon-info.

The output from this:
`size: PropTypes.oneOf(["small", "medium", "large"])`

needs to be matchable with the output from this:
`"blue" | "green"`

**Comment by strothj** [comment]
I'l have a look at this in more detail next Sunday. I might need to get some more typing information passed from the loader to help with this.

**Comment by mhauens** [comment]
@strothj thank you very much!

**Comment by strothj** [comment]
I was looking into how this could work.

After experimenting a bit it's looking like we'd need some changes to the package `react-docgen-typescript`. I think we'd need to get the original types for symbols during the parsing process and attach them to the parsing output. I'm not sure how feasible that would be.

I looked into using pattern matching instead but there would be some ambiguities. I was able to get boolean to work simple enough ("bool" vs "boolean").

If someone was up to the task of creating a pull request for `react-docgen-typescript` to pump the original types through to the outputted docgen structure (in the parse function), I'd update the Webpack loader to push it through.

**Comment by mhauens** [comment]
I created an issue for this
https://github.com/styleguidist/react-docgen-typescript/issues/117

**Comment by fabb** [comment]
Is there any update on this? In the linked `react-docgen-typescript` issue, there is an open question of the maintainer on what exactly is needed.

**Comment by fabb** [comment]
Interestingly, when defining a StatelessComponent by inheriting from `: SFC<MyProps>`, the smart knobs do not appear, when just removing it, they do (only when destructuring the `props`).

Working:
```
const Checkbox = ({prop1, prop2, prop3}: MyProps) => {}
```

Not working:
```
const Checkbox: SFC<CheckboxProps & TestingProps> = ({prop1, prop2, prop3}: MyProps) => {}
```

Any idea why?
