### ISSUE TITLE
Storybook 5 Support

### ISSUE THREAD

**Issue by mick-feller** [storybookjs/addon-smart-knobs#44]
Any plans on supporting Storybook 5?

Seems to be not working and getting peer dependency issue's.

Thanks

**Comment by favri** [comment]
Same question here guys!

Thanks for your work.

**Comment by mboudriga** [comment]
Is there any intent to get this working with storybook 5? 

Thanks for all the work you've done so far!

**Comment by daverau-optimizely** [comment]
Would love to see Smart Knobs become a Storybook default. 

Adding knobs code to each story is time consuming and a form of zombie documentation since props quickly become out of date.

**Comment by hakan-bilgin** [comment]
It should be absolutely a storybook default. Knob definitions can be outdated easily after prop changes.

**Comment by ndelangen** [comment]
FIXED in 5.0.0 which I just released
