### ISSUE TITLE
Undefined propType breaks render

### ISSUE THREAD

**Issue by weslleyaraujo** [storybookjs/addon-smart-knobs#5]
So what I found out was that whenever you have a prop declared in your component but not specified under `ComponentName.propTypes { ... }` will break storybook render

You can reproduce it by using the following:

![screen shot 2017-03-16 at 2 18 08 pm](https://cloud.githubusercontent.com/assets/2286385/23997701/bcbbb1d6-0a52-11e7-880c-74a869272f1b.png)

You can see that the prop `object` is not specified under propTypes, which causes:

![screen shot 2017-03-16 at 1 50 11 pm](https://cloud.githubusercontent.com/assets/2286385/23997719/d034b14a-0a52-11e7-9ad7-e08dd7349914.png)

It took me a while debugging to find out exactly what was going on, that could easily be solved by adding a check on `withSmartKnobs` :

```js
export const withSmartKnobs = (story, context) => {
  const component = story(context)
  const { __docgenInfo: { props } = { props: { } } } = component.type
  const defaultProps = {
    ...(component.type.defaultProps || {}),
    ...component.props
  }

  const finalProps = Object.keys(props).reduce((acc, n) => {
    const item = props[n];
    if (!item.type) {
      console.warn(`There is a prop with defaultValue ${item.defaultValue.value} but it wasnt specified on element.PropTypes. Check story: "${context.kind}".`);
      return acc;
    }

    return {
      ...acc,
      [n]: item,
    };
  }, {});

  return withKnobs(() => cloneElement(component, resolvePropValues(finalProps, defaultProps)), context)
}

```

which would look like this on console:

![screen shot 2017-03-16 at 2 43 10 pm](https://cloud.githubusercontent.com/assets/2286385/23998709/3f08c69e-0a56-11e7-8646-8f4d9552ec0d.png)

I would be glad to send a PR if you are okay with that, great work on the addon btw ;)

**Comment by lucasconstantino** [comment]
@weslleyaraujo you are very welcome to submit a pull request, if you can ;)

**Comment by danielduan** [comment]
This looks like it's been fixed, please reopen if it hasn't been.
