### ISSUE TITLE
Falsy default props are coerced to string, making knobs unusable

### ISSUE THREAD

**Issue by chriszarate** [storybookjs/addon-smart-knobs#73]
Thanks for the great addon! This is exactly what I looked for when I first learned about knobs.

My first implementation exposed an issue with this addon's treatment of `defaultProps`. Anything that's falsy is coerced to a string. That means that if I create a `defaultProp` for a boolean type:

```js
MyComponent.propTypes = {
  loading: PropTypes.bool,
};

MyComponent.defaultProps = {
  loading: false,
};
```

... the associated knob will receive a default value of `"false"` (the string "false"). Since non-empty strings are truthy, the component will interpret the prop as `true`. My knob is therefore useless, as both the unchecked / default value and the checked value are interpreted as true. The same is true for other falsy `defaultProp` values like `0`, `''`, and `null`.

This issue is easy to replicate in this repo. Clone it and add `defaultProp`s to `example/stories/SmartKnobedComponent.js`:

```js
SmartKnobedComponent.defaultProps = {
  bool: false,
  number: 0,
  string: '',
  func: null,
  oneOf: 'one',
  object: {},
  element: null,
  node: '',
}
```

Then run `npm run storybook`. This will produce a prop table like this, where all the falsy values are strings:

![problem](https://user-images.githubusercontent.com/739304/74496775-ba48e380-4ea9-11ea-8b48-a9ff18c2ea91.png)

It will also produce lots of `propType` warnings in the console because we are passing strings instead of the expected types:

```
Warning: Failed prop type: Invalid prop `bool` of type `string` supplied to `SmartKnobedComponent`, expected `boolean`.
```

I'll open a PR shortly to address this.

**Comment by chriszarate** [comment]
Here is the PR: https://github.com/storybookjs/addon-smart-knobs/pull/74

**Comment by mritunjayz** [comment]
this PR solves this issue, waiting to get it merged. we are using it at Hackerrank.

**Comment by Axfan** [comment]
Please merge the PR 🙏
