### ISSUE TITLE
Merge this into storybook core repo?

### ISSUE THREAD

**Issue by ndelangen** [storybookjs/addon-smart-knobs#9]
Hey, love the plugin!

I think this should be part of storybook core really!

Can you join us in the storybook slack?
https://storybooks-slackin.herokuapp.com/

That way we can keep you updated on the upcoming 3.0.0 release! 

❤️ storybook team

**Comment by ndelangen** [comment]
I've invited you into an organisation, if you could migrate this repo into that organisation, I'll take care of merging everything, and it would also be great if you could add me as a maintainer to the npm package.

I hope to hear from you!

**Comment by lucasconstantino** [comment]
@ndelangen sure, I can move it... but I can't seem to find the invitation! :/
